# Source: cluster-api-aws/templates/machine-pool.yaml
apiVersion: cluster.x-k8s.io/v1beta1
kind: MachinePool
metadata:
  name: cfpujazhv-mp-taco
  namespace: cfpujazhv
spec:
  clusterName: cfpujazhv
  replicas: 3
  template:
    metadata:
      labels:
            servicemesh: enabled
            taco-ingress-gateway: enabled
            taco-lma: enabled
    spec:
      bootstrap:
        dataSecretName: ""
      clusterName: cfpujazhv
      infrastructureRef:
        apiVersion: infrastructure.cluster.x-k8s.io/v1beta2
        kind: AWSManagedMachinePool
        name: cfpujazhv-mp-taco
        namespace: cfpujazhv
      version: v1.22.5

